library/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views
from .views import  BookCreateView, BookDetailView, BookDeleteView, BookHomeListView, BookAdminListView


app_name = 'library'

urlpatterns = [
    path('', BookHomeListView.as_view(), name='home'),
    path('library/books/', BookAdminListView.as_view(), name='books'),
    path('library/book_register/', BookCreateView.as_view(), name='book_register'),
    path('library/book/<int:pk>/', BookDetailView.as_view(), name='book_detail'),
    path('library/book/<int:pk>/delete/', BookDeleteView.as_view(), name='delete_book'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library_management_web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('users.urls')),
    path('', include('library.urls')),
]

users/urls.py
from django.urls import path
from .views import CustomLoginView, SignUpView

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),  # Usa o login customizado
    path('signup/', SignUpView.as_view(), name='signup'),
]

templates/partials/footer.html
<footer class="footer mt-3 py-3 bg-light">
  <div class="container text-center">
      <span class="text-muted">My Library &copy; 2024</span>
  </div>
</footer>

templates/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">My Library</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url "library:books" %}">Livros</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Usuários</a>
          </li>
        </ul>
        
        <!-- Alinha os itens de autenticação à direita -->
        <ul class="navbar-nav ms-auto">
          {% if user.is_authenticated %}
            <li class="nav-item">
                <form method="POST" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Logout</button>
                </form>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'signup' %}">Signup</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>


  