library/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views
from .views import  BookCreateView, BookDetailView, BookDeleteView, BookHomeListView, BookAdminListView


app_name = 'library'

urlpatterns = [
    path('', BookHomeListView.as_view(), name='home'),
    path('library/books/', BookAdminListView.as_view(), name='books'),
    path('library/book_register/', BookCreateView.as_view(), name='book_register'),
    path('library/book/<int:pk>/', BookDetailView.as_view(), name='book_detail'),
    path('library/book/<int:pk>/delete/', BookDeleteView.as_view(), name='delete_book'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library_management_web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('users.urls')),
    path('', include('library.urls')),
]

users/urls.py
from django.urls import path
from .views import CustomLoginView, SignUpView

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),  # Usa o login customizado
    path('signup/', SignUpView.as_view(), name='signup'),
]

library/models.py
from django.db import models
from users.models import User
from django.conf import settings

class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    year = models.CharField(max_length=4)
    genre = models.CharField(max_length=100)
    isbn = models.CharField(max_length=13, unique=True)
    avaible = models.BooleanField(default=True)
    cover_image = models.ImageField(upload_to='book_covers/', blank=True, null=True)
    synopsis = models.TextField(null=True, blank=True)
    def __str__(self):
        return  self.title

class Loan(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    loan_date = models.DateTimeField(auto_now_add=True)
    return_date = models.DateField()
    returned = models.BooleanField(default=False)

library/forms.py
from django import forms
from .models import Book
from datetime import datetime

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'genre', 'year', 'isbn', 'cover_image', 'synopsis', 'avaible']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'id': 'book_title'}),
            'author': forms.TextInput(attrs={'class': 'form-control', 'id': 'book_author'}),
            'genre': forms.TextInput(attrs={'class': 'form-control', 'id': 'book_genre'}),
            'year': forms.TextInput(attrs={'class': 'form-control', 'id': 'book_year'}),
            'isbn': forms.TextInput(attrs={'class': 'form-control', 'id': 'book_isbn'}),
            'cover_image': forms.ClearableFileInput(attrs={'class': 'form-control', 'id': 'book_cover'}),
            'synopsis': forms.Textarea(attrs={'class': 'form-control', 'aria-label': 'With textarea'}),
            'avaible': forms.CheckboxInput(attrs={'class': 'form-check-input', 'id': 'book_avaible'}),
        }

    def clean_title(self):
        title = self.cleaned_data.get('title')
        if title.isnumeric():
            raise forms.ValidationError("O título não pode conter apenas números.")
        return title

    def clean_author(self):
        author = self.cleaned_data.get('author')
        if author.isnumeric():
            raise forms.ValidationError("O nome do autor não pode conter apenas números.")
        return author

    def clean_year(self):
        year = self.cleaned_data.get('year')
        current_year = datetime.now().year
        if not year.isnumeric():
            raise forms.ValidationError("O ano de publicação deve conter apenas números.")
        if int(year) > current_year:
            raise forms.ValidationError("O ano de publicação não pode ser maior que o ano atual.")
        if len(str(year)) < 3:
            raise forms.ValidationError("O ano de publicação deve conter pelo menos 3 dígitos.")
        return year

    def clean_isbn(self):
        isbn = self.cleaned_data.get('isbn')
        if not isbn.isnumeric():
            raise forms.ValidationError("O código ISBN deve conter apenas números.")
        if Book.objects.filter(isbn=isbn).exists():
            raise forms.ValidationError("Este ISBN já está cadastrado para outro livro.")
        return isbn
    
    def clean_genre(self):
        genre = self.cleaned_data.get('genre')
        if genre.isnumeric():
            raise forms.ValidationError("O gênero literário não deve conter apenas números.")
        return genre

    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get('title')
        author = cleaned_data.get('author')
        genre = cleaned_data.get('genre')

        # Valida campos vazios
        if not title or not author or not genre:
            raise forms.ValidationError("Todos os campos devem ser preenchidos.")
        return cleaned_data

library/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import CreateView, DetailView, DeleteView
from django.views.generic.list import ListView
from django.contrib import messages
from django.contrib.messages import constants
from django.urls import reverse_lazy
from django.db import transaction
from .models import Book
from .forms import BookForm


class BookHomeListView(ListView):
    model = Book    
    template_name = 'home.html'


class BookAdminListView(ListView):
    model = Book    
    template_name = 'books.html'


class BookCreateView(CreateView):
    model = Book
    form_class = BookForm
    template_name = 'book_register.html'
    success_url = reverse_lazy('library:home')
    
    @transaction.atomic
    def form_valid(self, form):
        messages.add_message(self.request, constants.SUCCESS, 'Livro cadastrado com sucesso!')
        return super().form_valid(form)


class BookDetailView(DetailView):
    model = Book
    template_name = 'book_details.html'
    context_object_name = 'book'


class BookDeleteView(DeleteView):
    model = Book
    template_name = 'delete_book.html'
    success_url = reverse_lazy('library:books')
    
    @transaction.atomic
    def form_valid(self, form):
        messages.add_message(self.request, constants.SUCCESS, 'Livro deletado com sucesso!')
        return super().form_valid(form)

library/templates/book_details.html
{% extends 'base_generic.html' %}

{% block content %}
<div class="container mt-4 d-flex justify-content-center">
    <div class="card" style="max-width: 800px; width: 100%;">
        <div class="row g-0">
            <div class="col-md-8 p-3">
                <h2>{{ book.title }}</h2>
                <p><strong>Autor:</strong> {{ book.author }}</p>
                <p><strong>Gênero:</strong> {{ book.genre }}</p>
                <p><strong>Ano de publicação:</strong> {{ book.year }}</p>
                <p><strong>ISBN:</strong> {{ book.isbn }}</p>
                <p><strong>Disponível:</strong> {{ book.avaible|yesno:"Sim,Não" }}</p>
                
                <div class="mt-3">
                    <a href="#" class="btn btn-primary">Editar</a>
                    <a href="{% url "library:delete_book" book.id %}" class="btn btn-danger">Excluir</a>
                </div>
            </div>
            {% if book.cover_image %}
                <div class="col-md-4 p-3">
                    <img src="{{ book.cover_image.url }}" class="img-fluid" alt="Capa de {{ book.title }}" style="height: 100%; object-fit: cover;">
                </div>
            {% else %}
                <div class="col-md-4 p-3">
                    <img src="https://dummyimage.com/200x250/787878/fff&text=No+image" class="img-fluid" alt="Capa de {{ book.title }}" style="height: 100%; object-fit: cover;">
                </div>
            {% endif %}
        </div>

        <!-- Sinopse abaixo de tudo -->
        <div class="row mt-4">
            <div class="col-md-12 p-3">
                <h3>Sinopse</h3>
                <p>{{ book.synopsis }}</p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

library/templates/book_register.html
{% extends "base_generic.html" %}

{% block content %}

<h2 class="text-center">Cadastro de Livros</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-4 mb-3">
            <label for="book_title" class="form-label">Título</label>
            {{ form.title }}
            {% if form.title.errors %}
                <div class="text-danger">
                    {{ form.title.errors }}
                </div>
            {% endif %}
        </div>
        <div class="col-md-4 mb-3">
            <label for="book_author" class="form-label">Autor</label>
            {{ form.author }}
            {% if form.author.errors %}
                <div class="text-danger">
                    {{ form.author.errors }}
                </div>
            {% endif %}
        </div>
        <div class="col-md-4 mb-3">
            <label for="book_genre" class="form-label">Gênero Literário</label>
            {{ form.genre }}
            {% if form.genre.errors %}
                <div class="text-danger">
                    {{ form.genre.errors }}
                </div>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 mb-3">
            <label for="book_year" class="form-label">Ano de publicação</label>
            {{ form.year }}
            {% if form.year.errors %}
                <div class="text-danger">
                    {{ form.year.errors }}
                </div>
            {% endif %}
        </div>
        <div class="col-md-4 mb-3">
            <label for="book_isbn" class="form-label">Código ISBN</label>
            {{ form.isbn }}
            {% if form.isbn.errors %}
                <div class="text-danger">
                    {{ form.isbn.errors }}
                </div>
            {% endif %}
        </div>
        <div class="col-md-4 mb-3">
            <label for="book_cover" class="form-label">Capa do livro</label>
            {{ form.cover_image }}
            {% if form.cover_image.errors %}
                <div class="text-danger">
                    {{ form.cover_image.errors }}
                </div>
            {% endif %}
        </div>
    </div>
    <div class="mb-3">
        <label for="book_synopsis" class="form-label">Sinopse</label>
        {{ form.synopsis }}
        {% if form.synopsis.errors %}
            <div class="text-danger">
                {{ form.synopsis.errors }}
            </div>
        {% endif %}
    </div>
    <div class="mb-3 form-check">
        {{ form.avaible }} 
        <label class="form-check-label" for="book_avaible">Disponível</label>
    </div>
    <button type="submit" class="btn btn-primary">Cadastrar</button>
</form>
{% endblock content %}

library/templates/books.html
{% extends "base_generic.html" %}

{% block content %}
    <h1 class="text-center">Gerenciameto de Livros</h1>
    <div class="d-flex justify-content-between align-items-end">
        <span><i>* Selecione um livro para editar</i></span>
        <a class="btn btn-primary" href="{% url "library:book_register" %}">Cadastrar novo livro</a>
    </div>
    <table class="table table-hover mt-3">
        <thead class="table-light text-center">
            <th>Título</th>
            <th>Autor</th>
            <th>Publicação</th>
            <th>Gênero Literário</th>
            <th>ISBN</th>
            <th>Disponibilidade</th>
            <th>Data do empréstimo</th>
            <th>Data de retorno</th>
        </thead>
        {% for book in object_list %}
            <tr class="text-center">
                <td><a href="{% url "library:book_detail" book.id %}">{{ book.title }}</a></td>
                <td><a href="{% url "library:book_detail" book.id %}">{{ book.author }}</a></td>
                <td><a href="{% url "library:book_detail" book.id %}">{{ book.year }}</a></td>
                <td><a href="{% url "library:book_detail" book.id %}">{{ book.genre }}</a></td>
                <td><a href="{% url "library:book_detail" book.id %}">{{ book.isbn }}</a></td>
                <td><a href="{% url "library:book_detail" book.id %}">Indisponível</a></td>
                <td><a href="{% url "library:book_detail" book.id %}">14/10/2024</a></td>
                <td><a href="{% url "library:book_detail" book.id %}">31/10/2024</a></td>
            </tr>
        {% endfor %}
    </table>
{% endblock content %}

library/templates/delete_book.html
{% extends "base_generic.html" %}

{% block content %}
  <h2>Tem certeza de que deseja excluir o livro "{{ object.title }}"?</h2>

  <form method="POST"> 
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Excluir</button>
    <a href="{% url 'library:book_detail' book.id%}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock %}

library/templates/home.html
{% extends 'base_generic.html' %}

{% block content %}

<div class="row row-cols-1 row-cols-md-5 g-4">
{% for book in object_list %}
    <div class="col">
        <div class="card">
            {% if book.cover_image %}
                <img src="{{ book.cover_image.url }}" class="card-img-top" alt="Capa de {{ book.title }}">
            {% else %}
                <img src="https://dummyimage.com/200x250/787878/fff&text=No+image" class="card-img-top" alt="Capa de {{ book.title }}">
            {% endif %}
            <div class="card-body">
                <p class="card-title padding-card">{{book}}</p>
                <div>
                    <spam class="card-bold margin-card-body">Author: </spam>
                    <spam class="card-text">{{book.author}}</spam>                    
                </div>
                <div>
                    <spam class="card-bold margin-card-body">Publicação: </spam>
                    <spam class="card-text">{{book.year}}</spam>
                </div>
                <div>
                    <spam class="card-bold margin-card-body">ISBN: </spam>
                    <spam class="card-text">{{book.isbn}}</spam>
                </div>
            </div>
        </div>
    </div>
{% endfor %}
</div>

{% endblock content %}